# Generated by Django 4.0.4 on 2022-05-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=500)),
                ('date_of_creation', models.DateField()),
            ],
        ),
    ]
